# coding=utf-8

"""
Django settings for siteRoot project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

debug = not os.environ.get("APP_NAME", "")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'irlpa^z03nqxb1@n)q5z8z3!6v#@2qs30lg!!)-$!-an9f$3l+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["23.83.243.206", "127.0.0.1", "localhost", ".duan-ya.com"]

# Application definition

INSTALLED_APPS = [
    'suit',
    'accounts',  # 自定义用户系统
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',  # flatpages应用
    'siteRoot',
    'blog',
    'music',
    'fileManage',
]

# suit 后台主题配置项
SUIT_CONFIG = {
    'ADMIN_NAME': u'断崖上的风',
    'HEADER_DATE_FORMAT': 'Y-m-j l',
    'HEADER_TIME_FORMAT': 'H:i',
    'MENU': (
        {'app': 'sites', 'label': u'站点管理'},
        {'app': 'flatpages', 'label': u'页面管理'},
        {'app': 'accounts', 'label': u'账户管理'},
        {'app': 'auth', 'label': u'用户组管理'},
        {'app': 'blog', 'label': u'博客管理'},
        {'app': 'filemanage', 'label': u'文件管理'},
        # {'app': 'music', 'label': u'音乐'},
        # {'app': 'photogallery', 'label': u'相册'},
    ),
}

MIDDLEWARE_CLASSES = [

    # 'django.middleware.cache.UpdateCacheMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # POST控制中间件
    'libs.MiddleWare.PostController.PostController',

    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # flatpages中间件
    'django.contrib.flatpages.middleware.Http404',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',

    # Etag动态缓存中间件
    'libs.MiddleWare.EtagMiddleWare.EtagMiddleware',

    # 'django.middleware.cache.FetchFromCacheMiddleware',

]

APPEND_SLASH = True  # url最后自动加 /

ROOT_URLCONF = 'siteRoot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siteRoot.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'duan-ya',
        'USER': 'root',
        'PASSWORD': 'password',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    # 'blog': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'blog',
    #     'USER': 'root',
    #     'PASSWORD': 'password',
    #     'HOST': '127.0.0.1',
    #     'PORT': '3306',
    # }
}

# use multi-database in django
# DATABASE_ROUTERS = ['siteRoot.database_router.DatabaseAppsRouter']
# DATABASE_APPS_MAPPING = {
#     # example:
#     # 'app_name':'database_name',
#     'blog': 'blog',
# }

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

SITE_ID = 1

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # 配置开发环境静态文件根目录
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media 文件处理
if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    MEDIA_ROOT = "/media"
# if debug:
MEDIA_URL = '/media/'
# else:
#     MEDIA_URL = "http://duanyablog-media.stor.sinaapp.com/"  # 这里就写你的应用名和domain

MAX_SIZE = 10 * 1024 * 1024  # 限制最大上传文件

# 默认用户表扩展
AUTH_USER_MODEL = 'accounts.User'

# 缓存管理
# 暂时使用数据表缓存
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
        'TIMEOUT': 600,
        'OPTIONS': {
            'MAX_ENTRIES': 2000
        }
    }
}

CACHE_MIDDLEWARE_SECONDS = 180

CACHE_MIDDLEWARE_KEY_PREFIX = "blog.duan-ya.com"
